server:
  port: 8764
spring:
  application:
    name: springcloud-tigong-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: springcloud-xiaofei
    api-b:
      path: /api-b/**
      serviceId: springcloud-tigong
  prefix: /aaa
